### ISSUE TITLE
Please update for Fastify >= 1.x

### ISSUE THREAD

**Issue by sjorsjes** [gj/fastify-ws#9]
I want to update to fastify 2.0 but this is the only plugin i use that is not ready for it. I tried to do a PR but I have no rights to do commits.

**Comment by gj** [comment]
@imrefazekas has helpfully opened a PR (#10) if you'd like to take a look @sjorsjes 🙂 

I'll test the changes out after work today.

**Comment by sjorsjes** [comment]
That are the same changes as that I wanted to do a PR for. Works like a charm on Fastify 2.x, and should be backwords compatible with lower versions as well, because I don't think there were breaking changes in the fastify-plugin.

**Comment by gj** [comment]
Awesome — thanks for the info @sjorsjes !

**Comment by gj** [comment]
Published version `1.0.1` to NPM — maintains the same API as `1.0.0` and works with Fastify `1.7.0` - `2.x`.

Beware that since `1.0.0` was published, the creator of the `uws` package has decided to abandon that project, so my advice going forward is to rely on the stable `ws` package (the default option for `fastify-ws`).
